name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  build:
    name: "Build docker container"
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: docker-compose build
  instal-server-dependencies:
    name: "Install server dependencies"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: docker-compose run php composer install
  run-tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    needs: instal-server-dependencies
    steps:
      - run: docker-compose run php ./vendor/bin/phpunit
